name = "gwitter"
main = "worker.js"
compatibility_date = "2023-10-30"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[site]
bucket = "./dist"
entry-point = "worker.js"

[vars]
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""

# 运行示例：wrangler dev
# 部署示例：wrangler publish 